---
- name: install git, jdk, maven
  hosts: build
  become: yes

  tasks:
  - name: install git package
    apt:
      name: git
      update_cache: yes

  - name: install jdk package
    apt:
      name: default-jdk
      update_cache: yes

  - name: install maven package
    apt:
      name: maven
      update_cache: yes

  - name: git clone project "boxfuse"
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /usr/local/project
      clone: yes

  - name: start mvn
    shell: "cd /usr/local/project/ &&  mvn clean install"
    become: yes
    register: project_result

  - name: mvn result
    debug:
      var: project_result

  - name: file.war to prod
    fetch:
      src: /usr/local/project/target/hello-1.0.war
      dest: /tmp/project/
      flat: yes
  
- name: install jdk, tomcat
  hosts: prod
  become: yes

  tasks:
  - name: install jdk package
    apt:
      name: default-jdk
      update_cache: yes

  - name: install tomcat package
    apt:
      name: tomcat9
      update_cache: yes

  - name: copy file.war
    copy:
      src: /tmp/project/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/